name: Tests

on: [push]

jobs:
    hadolint:
      name: Check wth hadolin
      runs-on: ubuntu-latest
      containers: hadolint/hadolint
      steps:
        - name: Checkout source code 
          uses: actions/checkout@v2
        - name: Check image
          run: hadolint Dockerfile

    test_unit:
        name: test
        runs-on: ubuntu-latest
        container: dockerlennyy/blog_php
        steps:
          - name: run composer install
          run: composer install
          - name: do the test
          run: bin/phpunit
        
